name: Semgrep

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Semgrep Security Scan
        run: semgrep scan --config auto